apply plugin:'java'


group = 'cz.siret.prank'
version = '2.5.2'
description = "Fast Random Forest implementations for Weka. Streamlined version of Fans Supek's FastRandomForest."

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}


repositories {

    mavenCentral()
    mavenLocal()

}

jar {
    manifest {
        attributes 'Main-Class': 'cz.siret.prank.ffutils.Main'
    }
}

test {

    testLogging {
        events "failed" // "standardOut", "standardError", "passed", "skipped"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true

        showStandardStreams = false
    }

}

dependencies {
    implementation 'org.apache.commons:commons-lang3:3.17.0'
    implementation 'nz.ac.waikato.cms.weka:weka-dev:3.9.6'
    implementation 'com.carrotsearch:hppc:0.10.0'

    testImplementation 'junit:junit:4.13.2'
}
